import {
  H2,
  Link,
  MiniCode,
  P,
} from "@modules/shared/modules/markdown/components/Markdown/components"
import { ApiRoute, Body, Example, QueryParams, Try } from "../components"
import { EXAMPLE, PARAMS, BODY } from "@modules/docs/domain/core/sections/api/transform-schema"
import { SCHEMA } from "@modules/docs/domain/core/sections/concepts"

export default function En() {
  return (
    <>
      <ApiRoute />

      <H2 title={PARAMS} />

      <QueryParams />

      <H2 title={BODY} />

      <P>The following parameters must be defined on the request body</P>

      <Body />

      <H2 title={EXAMPLE} />

      <P>
        The following example shows the creation and transpilation of data generated by the{" "}
        <Link to={SCHEMA.redirect}>schema</Link> <MiniCode>Movie</MiniCode> to{" "}
        <MiniCode>json</MiniCode> format.
      </P>

      <Example />

      <Try />
    </>
  )
}
