export enum CONFIG_ACTIONS {
  SET_INITIAL_CONFIG = "SET_INITIAL_CONFIG",
  CHANGE_FILE_TYPE = "CHANGE_FILE_TYPE",
  CHANGE_SAVE_SCHEMA = "CHANGE_SAVE_SCHEMA",
  CHANGE_FILE_ARGUMENTS = "CHANGE_FILE_ARGUMENTS",
}
