export enum DATA_TYPES {
  MODULE_VALUE = "MODULE_VALUE",
  MIXED = "MIXED",
  REF = "REF",
  CUSTOM = "CUSTOM",
  SEQUENCE = "SEQUENCE",
  SEQUENTIAL = "SEQUENTIAL",
  ENUM = "ENUM",
  PROBABILITY = "PROBABILITY",
  PICK = "PICK",
}
