import {
  API_SECTION,
  CONCEPTS_SECTION,
  EXPORT_SECTION,
  FIELD_TYPES_SECTION,
  GET_STARTED_SECTION,
  MODULES_SECTION,
} from "../core/sections"

export const DOCS = [
  GET_STARTED_SECTION,
  CONCEPTS_SECTION,
  FIELD_TYPES_SECTION,
  MODULES_SECTION,
  EXPORT_SECTION,
  API_SECTION,
]
