export const DATA_TYPES = {
  SINGLE_VALUE: "SINGLE_VALUE",
  MIXED: "MIXED",
  REF: "REF",
  CUSTOM: "CUSTOM",
};

export const FIELDS_INPUT_TYPES = {
  SELECT: "SELECT",
  NUMBER: "NUMBER",
  TEXT: "TEXT",
  DATE: "DATE",
  FLOAT: "FLOAT",
  BOOLEAN: "BOOLEAN",
  CUSTOM_ARRAY: "CUSTOM_ARRAY",
};

export const CUSTOM_CODE = {
  JAVASCRIPT: "JAVASCRIPT",
  PYTHON: "PYTHON",
};
