export enum MODAL_ACTIONS {
  EDIT_DATASET,
  ADD_FIELD,
  ADD_DATASET,
  EDIT_FIELD,
  RENAME_DATASET,
  DELETE_DATASET,
  EXPORT_SELECT_DATASET,
  EXPORT_ALL_DATASETS,
  TEST_ENDPOINT,
  ADMIN_CREATE_API_DOC_SECTION,
}
