export const DATASETS_ACTIONS = {
  CREATE_NEW_DATASET: "CREATE_NEW_DATASET",
  ADD_NEW_FIELD: "ADD_NEW_FIELD",
  CHANGE_FIELD_NAME: "CHANGE_FIELD_NAME",
  DELETE_FIELD: "DELETE_FIELD",
  CHANGE_FIELD_DATATYPE: "CHANGE_FIELD_DATATYPE",
  CHANGE_DATASET_LIMIT: "CHANGE_DATASET_LIMIT",
  CHANGE_POSIBLE_NULL: "CHANGE_POSIBLE_NULL",
  CHANGE_TO_ARRAY_TYPE: "CHANGE_TO_ARRAY_TYPE",
  CHANGE_ARRAY_LIMITS: "CHANGE_ARRAY_LIMITS",
  CHANGE_DATASET_NAME: "CHANGE_DATASET_NAME",
};

export const CONFIG_ACTIONS = {
  SET_INITIAL_CONFIG: "SET_INITIAL_CONFIG",
  CHANGE_FILE_TYPE: "CHANGE_FILE_TYPE",
  CHANGE_SAVE_SCHEMA: "CHANGE_SAVE_SCHEMA",
  CHANGE_FILE_ARGUMENTS: "CHANGE_FILE_ARGUMENTS",
};
