export const DATASETS_ACTIONS = {
  CREATE_NEW_DATASET: "CREATE_NEW_DATASET",
  ADD_NEW_FIELD: "ADD_NEW_FIELD",
  CHANGE_FIELD_NAME: "CHANGE_FIELD_NAME",
  DELETE_FIELD: "DELETE_FIELD",
  SELECT_FIELD_TYPE: "SELECT_FIELD_TYPE",
  CHANGE_DATASET_LIMIT: "CHANGE_DATASET_LIMIT",
  CHANGE_POSIBLE_NULL: "CHANGE_POSIBLE_NULL",
};
