export const DATASETS_ACTIONS = {
  CREATE_NEW_DATASET: "CREATE_NEW_DATASET",
  ADD_NEW_FIELD: "ADD_NEW_FIELD",
  CHANGE_FIELD_NAME: "CHANGE_FIELD_NAME",
  DELETE_FIELD: "DELETE_FIELD",
  SELECT_FIELD_TYPE: "SELECT_FIELD_TYPE",
  CHANGE_DATASET_LIMIT: "CHANGE_DATASET_LIMIT",
  CHANGE_POSIBLE_NULL: "CHANGE_POSIBLE_NULL",
  CHANGE_TO_ARRAY_TYPE: "CHANGE_TO_ARRAY_TYPE",
  CHANGE_ARRAY_LIMITS: "CHANGE_ARRAY_LIMITS",
};

export const CONFIG_ACTIONS = {
  CHANGE_FILE_TYPE: "CHANGE_FILE_TYPE",
  CHANGE_SAVE_SCHEMA: "CHANGE_SAVE_SCHEMA",
};
